export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Practices } from './Practices'
export { default as WhyChooseUs } from './WhyChooseUs'
export { default as Reasons } from './Reasons'
export { default as CallToAction } from './CallToAction'
export { default as Search } from './Search'
export { default as Doctors } from './Doctors'
export { default as News } from './News'
export { default as Footer } from './Footer'

